CREATE DATABASE QLTIEMCHUNG
GO
USE QLTIEMCHUNG

GO
CREATE TABLE PHIEU_DANG_KY (
	MAPDK INT IDENTITY(100000,1),
	NGAYTIEM DATE,
	TRANGTHAI NVARCHAR(20),
	LOAI NVARCHAR(20),
	TONGTIEN MONEY,
	TRANGTHAITT NVARCHAR(20),
	SODOTTT INT,
	MAKH INT,
	MANV INT,
	PRIMARY KEY (MAPDK)
)
CREATE TABLE CT_DANG_KY (
	MAPDK INT,
	MAVC INT,
	SOLUONG INT,
	DONGIA MONEY,
	THANHTIEN MONEY,
	PRIMARY KEY (MAPDK, MAVC)
)
CREATE TABLE NHAN_VIEN (
	MANV INT IDENTITY(100,1),
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3),
	CMND VARCHAR(12),
	SDT CHAR(10),
	DIACHI NVARCHAR(50),
	TENLOAINV NVARCHAR(20),
	PRIMARY KEY (MANV)
)
CREATE TABLE HOA_DON (
	MAHD INT IDENTITY(1000000,1) PRIMARY KEY,
	NGAYLAP DATE,
	NOIDUNG NVARCHAR(200),
	TONGTIENTHANHTOAN MONEY,
	MAPDK INT,
	MANV INT,
	MAKH INT
)
CREATE TABLE VACCINE (
	MAVC INT IDENTITY(5000,1) PRIMARY KEY,
	TENVC NVARCHAR(200),
	LOAIVC NVARCHAR(100),
	LOSX VARCHAR(100),
	HSD DATE,
	MOTA NVARCHAR(200),
	SLTON INT,
	XUATXU NVARCHAR(100),
	PHANLOAI NVARCHAR(100)
)
 
CREATE TABLE KHACH_HANG (
	MAKH INT IDENTITY(2000,1),
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3),
	DIACHI NVARCHAR(50),
	SDT CHAR(10),
	CMND VARCHAR(12),
	LOAIKH NVARCHAR(20),
	MANGH INT,
	PRIMARY KEY(MAKH)
)

CREATE TABLE PHIEU_DAT_MUA(
	MAPD INT IDENTITY(2000000,1) PRIMARY KEY,
	TSLDAT INT,
	THANHTIEN MONEY,
	MANV INT,
	MAPDK INT
)
CREATE TABLE CHI_TIET_PHIEU_DAT (
	MAPD INT,
	MAVC INT,
	SLDAT INT,
	DONGIA MONEY,
	THANHTIEN MONEY,
	PRIMARY KEY(MAPD, MAVC)
)
CREATE TABLE CHI_TIET_GOI_TIEM(
	MAGOI INT,
	MAVC INT,
	SLANTIEM INT,
	PRIMARY KEY (MAGOI, MAVC)
)
CREATE TABLE NGUOI_GIAM_HO (
	MANGH INT IDENTITY(5000,1) PRIMARY KEY,
	HOTEN NVARCHAR(30),
	QUANHE NVARCHAR(30),
	SDT VARCHAR(10),
	CMND VARCHAR(12),
)
CREATE TABLE PHIEU_KHAM (
	MAPK INT IDENTITY(3000000,1) PRIMARY KEY,
	MABS INT,
	MAKH INT,
	NGAYKHAM DATETIME,
	NHIETDO INT,
	NHIPTIM INT,
	HUYETAP INT,
	KETLUAN NVARCHAR(200)
)
CREATE TABLE SO_TIEM_CHUNG (
	NGAYTIEM DATE,
	MAVC INT, 
	PHANUNG NVARCHAR(50),
	MAKH INT,
	PRIMARY KEY(NGAYTIEM, MAVC)
)
------ADD FOREIGN KEY
ALTER TABLE PHIEU_DANG_KY
ADD 
CONSTRAINT FK_PDK_NV
FOREIGN KEY (MANV) REFERENCES NHAN_VIEN (MANV),
CONSTRAINT FK_PDK_KH
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)

ALTER TABLE CT_DANG_KY
ADD 
CONSTRAINT FK_CTDK_PDK
FOREIGN KEY (MAPDK) REFERENCES PHIEU_DANG_KY(MAPDK),
CONSTRAINT FK_CTDK_VAC
FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC)

ALTER TABLE SO_TIEM_CHUNG
ADD
CONSTRAINT FK_SOTIEM_VAC
FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC),
CONSTRAINT FK_SOTIEM_KH
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG (MAKH)

ALTER TABLE HOA_DON
ADD
CONSTRAINT FK_HD_PDK
FOREIGN KEY (MAPDK) REFERENCES PHIEU_DANG_KY(MAPDK),
CONSTRAINT FK_HD_NV
FOREIGN KEY (MANV) REFERENCES NHAN_VIEN (MANV),
CONSTRAINT FK_HD_KH
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)

ALTER TABLE KHACH_HANG
ADD
CONSTRAINT FK_KH_NGH
FOREIGN KEY (MANGH) REFERENCES NGUOI_GIAM_HO (MANGH)

ALTER TABLE PHIEU_KHAM
ADD
CONSTRAINT FK_PHKHAM_NV
FOREIGN KEY (MABS) REFERENCES NHAN_VIEN (MANV),
CONSTRAINT FK_PHKHAM_KH
FOREIGN KEY (MAKH) REFERENCES KHACH_HANG (MAKH)

ALTER TABLE PHIEU_DAT_MUA
ADD
CONSTRAINT FK_PDM_NV
FOREIGN KEY (MANV) REFERENCES NHAN_VIEN (MANV),
CONSTRAINT FK_PDM_PDK
FOREIGN KEY (MAPDK) REFERENCES PHIEU_DANG_KY (MAPDK)

ALTER TABLE CHI_TIET_PHIEU_DAT
ADD
CONSTRAINT FK_CTPD_PD
FOREIGN KEY (MAPD) REFERENCES PHIEU_DAT_MUA (MAPD),
CONSTRAINT FK_CTPD_VAC
FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC)

ALTER TABLE CHI_TIET_GOI_TIEM
ADD
CONSTRAINT FK_CTGT_VAC
FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC),
CONSTRAINT FK_CTGT_GOITIEM
FOREIGN KEY (MAGOI) REFERENCES VACCINE (MAVC)

-- DROP DATABASE QLTIEMCHUNG